image: docker:latest

services:
  - docker:dind

stages:
  - build
  - package

before_script:
  - echo "Set up any global configurations here."



docker_package_frontend:
  stage: package
  before_script:
    
    - docker login -u abdellahah -p $DOCKER_HUB_PASSWORD
  script:
    - docker build -t abdellahah/devops-angular .
    - docker push abdellahah/devops-angular
