image: docker:latest

services:
  - docker:dind

stages:
  - build
  - package

before_script:
  - echo "Set up any global configurations here."

.generic_angular_job:
  include:
    - local: '/generic_angular_job.yml'

build_frontend:
  script:
    - echo "Generic file is included successfully."
  extends: generic_angular_job  # Extend the generic Angular job

docker_package_frontend:
  stage: package
  before_script:
    - export DOCKER_HOST=tcp://docker:2375
    - docker login -u abdellahah -p $DOCKER_HUB_PASSWORD
  script:
    - docker build -t abdellahah/devops-angular .
    - docker push abdellahah/devops-angular
